Controllers/BuysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Major_Project.Data;
using Major_Project.Models;
using Microsoft.AspNetCore.Authorization;

namespace Major_Project.Controllers
{
    [Authorize]
    public class BuysController : Controller
    {
        private readonly Major_ProjectContext _context;

        public BuysController(Major_ProjectContext context)
        {
            _context = context;
        }

        // GET: Buys
        public async Task<IActionResult> Index()
        {
            var major_ProjectContext = _context.Buy.Include(b => b.Car).Include(b => b.Customer).Include(b => b.Staff).Include(b => b.Store);
            return View(await major_ProjectContext.ToListAsync());
        }

        // GET: Buys/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buy = await _context.Buy
                .Include(b => b.Car)
                .Include(b => b.Customer)
                .Include(b => b.Staff)
                .Include(b => b.Store)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buy == null)
            {
                return NotFound();
            }

            return View(buy);
        }

        // GET: Buys/Create
        public IActionResult Create()
        {
            ViewData["CarId"] = new SelectList(_context.Car, "Id", "Id");
            ViewData["CustomerId"] = new SelectList(_context.Customer, "Id", "Id");
            ViewData["StaffId"] = new SelectList(_context.Staff, "Id", "Id");
            ViewData["StoreId"] = new SelectList(_context.Store, "Id", "Id");
            return View();
        }

        // POST: Buys/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CustomerId,StaffId,StoreId,CarId")] Buy buy)
        {
            if (ModelState.IsValid)
            {
                _context.Add(buy);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarId"] = new SelectList(_context.Car, "Id", "Id", buy.CarId);
            ViewData["CustomerId"] = new SelectList(_context.Customer, "Id", "Id", buy.CustomerId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "Id", "Id", buy.StaffId);
            ViewData["StoreId"] = new SelectList(_context.Store, "Id", "Id", buy.StoreId);
            return View(buy);
        }

        // GET: Buys/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buy = await _context.Buy.FindAsync(id);
            if (buy == null)
            {
                return NotFound();
            }
            ViewData["CarId"] = new SelectList(_context.Car, "Id", "Id", buy.CarId);
            ViewData["CustomerId"] = new SelectList(_context.Customer, "Id", "Id", buy.CustomerId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "Id", "Id", buy.StaffId);
            ViewData["StoreId"] = new SelectList(_context.Store, "Id", "Id", buy.StoreId);
            return View(buy);
        }

        // POST: Buys/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CustomerId,StaffId,StoreId,CarId")] Buy buy)
        {
            if (id != buy.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(buy);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BuyExists(buy.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarId"] = new SelectList(_context.Car, "Id", "Id", buy.CarId);
            ViewData["CustomerId"] = new SelectList(_context.Customer, "Id", "Id", buy.CustomerId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "Id", "Id", buy.StaffId);
            ViewData["StoreId"] = new SelectList(_context.Store, "Id", "Id", buy.StoreId);
            return View(buy);
        }

        // GET: Buys/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buy = await _context.Buy
                .Include(b => b.Car)
                .Include(b => b.Customer)
                .Include(b => b.Staff)
                .Include(b => b.Store)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buy == null)
            {
                return NotFound();
            }

            return View(buy);
        }

        // POST: Buys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var buy = await _context.Buy.FindAsync(id);
            _context.Buy.Remove(buy);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BuyExists(int id)
        {
            return _context.Buy.Any(e => e.Id == id);
        }
    }
}

Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Major_Project.Data;
using Major_Project.Models;
using Microsoft.AspNetCore.Authorization;

namespace Major_Project.Controllers
{
    public class CarsController : Controller
    {
        private readonly Major_ProjectContext _context;

        public CarsController(Major_ProjectContext context)
        {
            _context = context;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            return View(await _context.Car.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Car_Name,Car_Make,Car_Date,Car_Price")] Car car)
        {
            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Car_Name,Car_Make,Car_Date,Car_Price")] Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Car.FindAsync(id);
            _context.Car.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Car.Any(e => e.Id == id);
        }
    }
}

Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Major_Project.Data;
using Major_Project.Models;
using Microsoft.AspNetCore.Authorization;

namespace Major_Project.Controllers
{
    public class StaffsController : Controller
    {
        private readonly Major_ProjectContext _context;

        public StaffsController(Major_ProjectContext context)
        {
            _context = context;
        }

        // GET: Staffs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Staff.ToListAsync());
        }

        // GET: Staffs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // GET: Staffs/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Staff_Name,Staff_Last_Name,Staff_Address,Staff_Contact")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staff);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET: Staffs/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Staff_Name,Staff_Last_Name,Staff_Address,Staff_Contact")] Staff staff)
        {
            if (id != staff.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(staff);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET: Staffs/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staff = await _context.Staff.FindAsync(id);
            _context.Staff.Remove(staff);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffExists(int id)
        {
            return _context.Staff.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car_Major_Project</title>
    <!--Style-Sheets-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/components.css" rel="stylesheet" />
    <link href="~/css/responsee.css" rel="stylesheet" />
    <link href="~/owl-carousel/owl.carousel.css" rel="stylesheet" />
    <link href="~/owl-carousel/owl.theme.css" rel="stylesheet" />
    <link href="~/css/template-style.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <!--Style-Sheets-Ends-->
    <!--Scripts-->
    <script src="~/js/jquery-1.8.3.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/modernizr.js"></script>
    <script src="~/js/responsee.js"></script>
    <script src="~/js/template-scripts.js"></script>
    <!--Script-Ends-->
</head>
<body>
    <header>
        <div id="topbar">
            <div class="line">
                <div class="s-12 m-6 l-6">
                    <p>CONTACT US: <strong>0800 200 200</strong> | <strong>contact@sampledomain.com</strong></p>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Dream Car</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Customers" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Index">Staff</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cars" asp-action="Index">Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Stores" asp-action="Index">Stores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Buys" asp-action="Index">Buy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <section>
        <!-- CAROUSEL -->
        <div id="carousel">
            <div id="owl-demo" class="owl-carousel owl-theme">
                <div class="item">
                    <img src="~/img/first1.jpg" alt="">
                    <div class="line">
                        <div class="text hide-s">
                            <div class="line">
                                <div class="prev-arrow hide-s hide-m">
                                    <i class="icon-chevron_left"></i>
                                </div>
                                <div class="next-arrow hide-s hide-m">
                                    <i class="icon-chevron_right"></i>
                                </div>
                            </div>
                            <h2>Buy All The New Cars</h2>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <img src="~/img/second2.jpg" alt="">
                    <div class="line">
                        <div class="text hide-s">
                            <div class="line">
                                <div class="prev-arrow hide-s hide-m">
                                    <i class="icon-chevron_left"></i>
                                </div>
                                <div class="next-arrow hide-s hide-m">
                                    <i class="icon-chevron_right"></i>
                                </div>
                            </div>
                            <h2>Full-Fill Your Dreams</h2>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <img src="~/img/third3.jpg" alt="">
                    <div class="line">
                        <div class="text hide-s">
                            <div class="line">
                                <div class="prev-arrow hide-s hide-m">
                                    <i class="icon-chevron_left"></i>
                                </div>
                                <div class="next-arrow hide-s hide-m">
                                    <i class="icon-chevron_right"></i>
                                </div>
                            </div>
                            <h2>Advance & Upgraded</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <section>
        <!--Contact Us Form-->
        <div id="contact">
            <div class="line">
                <h2 class="section-title">Contact Us</h2>
                <div class="margin">
                    <div class="s-12 m-12 l-3 hide-m hide-s margin-bottom right-align">
                        <img src="img/contact.jpg" alt="">
                    </div>
                    <div class="s-12 m-12 l-4 margin-bottom right-align">
                        <h3>Only Spot - Car Sellers</h3>
                        <address>
                            <p><strong>Adress:</strong> 25 Springs Road, East Tamaki</p>
                            <p><strong>Country:</strong> Auckland - New Zealand</p>
                            <p><strong>E-mail:</strong> info@visiondesign.sk</p>
                        </address>
                    </div>
                </div>
            </div>
        </div>
        <!-- MAP -->
        <div id="map-block">
            <iframe src="https://www.google.com/maps/d/embed?mid=1mhGsju95P4N5bIGHHMyoZCeGbXg&hl=en" width="100%" height="450" frameborder="0" style="border:0"></iframe>
        </div>
    </section>

    <footer class="border-top footer text-muted">
        <div class="line">
            <div class="s-12 l-6">
                <p>Copyright 2015, Car Management - Project</p>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script src="~/owl-carousel/owl.carousel.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            var theme_slider = $("#owl-demo");
            $("#owl-demo").owlCarousel({
                navigation: false,
                slideSpeed: 300,
                paginationSpeed: 400,
                autoPlay: 6000,
                addClassActive: true,
                // transitionStyle: "fade",
                singleItem: true
            });
            $("#owl-demo2").owlCarousel({
                slideSpeed: 300,
                autoPlay: true,
                navigation: true,
                navigationText: ["&#xf007", "&#xf006"],
                pagination: false,
                singleItem: true
            });

            // Custom Navigation Events
            $(".next-arrow").click(function () {
                theme_slider.trigger('owl.next');
            })
            $(".prev-arrow").click(function () {
                theme_slider.trigger('owl.prev');
            })
        });
    </script>
</body>
</html>